### ISSUE TITLE
Video Problems

### ISSUE THREAD

**Issue by kingunlim** [fhriley/docker-firefox#2]
Hi, First of all, thank you very much for your raspberry firefox build ;)
i want to use it on an old ipad and safari wont open it i would think the vnc server is to new for safari on ios 9.3.5?
but with an old vnc app it works, so not a big problem.
just curious if you know what the problem is?

the bigger problem, i can't view my cams in firefox, i see in the options: firefox says at the next start it installs h264 but that never happend?
do you maybe know what i can do?

best regards

**Comment by fhriley** [comment]
This doesn't have any hardware acceleration so I doubt h264 will work.
