### ISSUE TITLE
Password protection.

### ISSUE THREAD

**Issue by Dethkiller15** [fhriley/docker-firefox#4]
in supervisord I see that there are options to add a username and password but I myself cant seem to get it to work.

Right now I have a small whitelist of IPs that are able to use the URL but I want to take that down so I dont have to edit it every time I attempt to connect while I am out and about.

**Comment by Redst0neFlux** [comment]
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by fhriley** [comment]
This doesn't belong in this image. If you want it secured, put it behind a VPN or a reverse proxy that does authentication. For external access, I personally use two methods:

1. [Wireguard](https://www.wireguard.com/) VPN - this is my preferred method and all of my personal devices are set up to use it
2. [Cloudflared](https://github.com/cloudflare/cloudflared) - I use this method when I'm at work and need to access it from a work computer
